In [1]:
#2.3.1
import numpy as np

def relu(X):
   return np.maximum(0,X)

input = np.array([1, 1, 1, 1, 1])
W = np.array([[5,78,2,34,0],
              [6,79,3,35,1],
              [7,80,4,36,2]])

b = np.array([0.5, 0.5, 0.5,])

np.dot(W, input)
output = relu(np.dot(W, input) + b)
print(output)
output = np.maximum(np.dot(W, input) + b, 0)
print(output)
output = np.dot(W, input)
print(output)
print(input.shape)
print(W.shape)

[119.5 124.5 129.5]
[119.5 124.5 129.5]
[119 124 129]
(5,)
(3, 5)


In [23]:
#2.3.2
x = np.random.random((6,2,4))
print(x.shape)
print(x)

y = np.random.random((2,4))
print(y.shape)
print(y)

z = x + y
print(z.shape)
print(z)

(6, 2, 4)
[[[0.92751912 0.52879972 0.93812538 0.41929677]
  [0.50049694 0.86305334 0.34537808 0.02068223]]

 [[0.94893182 0.84044469 0.22979353 0.10864611]
  [0.96368122 0.51172067 0.47990143 0.02711349]]

 [[0.03296704 0.84472111 0.39094686 0.36011601]
  [0.83862444 0.63449529 0.41623925 0.01586464]]

 [[0.02799573 0.41917532 0.92215086 0.59079403]
  [0.01185975 0.85472551 0.22029066 0.5483143 ]]

 [[0.93679214 0.86291168 0.92346979 0.71774594]
  [0.96090943 0.12771859 0.27726472 0.21189267]]

 [[0.63150129 0.6653529  0.88400378 0.01679351]
  [0.88867405 0.30872394 0.24571546 0.25597467]]]
(2, 4)
[[0.88041026 0.60897425 0.89410688 0.14528511]
 [0.64984636 0.75944077 0.09634732 0.36429285]]
(6, 2, 4)
[[[1.80792938 1.13777397 1.83223226 0.56458187]
  [1.1503433  1.62249411 0.44172541 0.38497509]]

 [[1.82934208 1.44941894 1.12390041 0.25393122]
  [1.61352758 1.27116143 0.57624875 0.39140634]]

 [[0.9133773  1.45369536 1.28505374 0.50540112]
  [1.4884708  1.39393605 0.51258657 0.38015749

In [14]:
#2.3.2
x = np.random.random((6,3,2,4))
print(x.shape)
print(x[1])

y = np.random.random((2,4))
print(y.shape)
print(y[1])

z = np.maximum(x,y)
print(z.shape)
print(z[1])

(6, 3, 2, 4)
[[[0.26922773 0.5571577  0.10552864 0.14529972]
  [0.85519478 0.38976463 0.78168139 0.01683833]]

 [[0.2392117  0.58854396 0.42475202 0.35821531]
  [0.69339302 0.17412345 0.83509467 0.06364545]]

 [[0.0227242  0.16425072 0.41830408 0.59086963]
  [0.01799123 0.82047735 0.85623521 0.44616332]]]
(2, 4)
[0.29449922 0.72960717 0.76279559 0.71833566]
(6, 3, 2, 4)
[[[0.81147544 0.5571577  0.14373244 0.28638223]
  [0.85519478 0.72960717 0.78168139 0.71833566]]

 [[0.81147544 0.58854396 0.42475202 0.35821531]
  [0.69339302 0.72960717 0.83509467 0.71833566]]

 [[0.81147544 0.16425072 0.41830408 0.59086963]
  [0.29449922 0.82047735 0.85623521 0.71833566]]]


In [20]:
#2.3.3
p = np.random.random((2,4))
print(p.shape)
print(p)

q = np.random.random((2,4))
print(q.shape)
print(np.transpose(q))

y = np.dot(p,np.transpose(q))
print(y.shape)
print(y)

(2, 4)
[[0.08523008 0.62845091 0.03169981 0.40049069]
 [0.72895537 0.23122785 0.33161044 0.14806672]]
(2, 4)
[[0.08564437 0.69225378]
 [0.6018142  0.45975242]
 [0.79645202 0.10236202]
 [0.66449333 0.48760233]]
(2, 2)
[[0.67688093 0.54645772]
 [0.56408829 0.71707166]]


In [28]:
#2.3.3
p = np.random.random((2))
print(p.shape)
print(p)

q = np.random.random((2))
print(q.shape)
print((q))

y = np.dot(p,(q))
print(y.shape)
print(y)

(2,)
[0.75401171 0.35014453]
(2,)
[0.66273333 0.62646466]
()
0.7190618675394861


In [38]:
#2.3.4
x = np.array([[0.,1.],[2.,3.],[4.,5.]])
print(x)
print(x.shape)

y = x.reshape([1,6])
print(y)
print(y.shape)

z = np.transpose(x)
print(z)
print(z.shape)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
(3, 2)
[[0. 1. 2. 3. 4. 5.]]
(1, 6)
[[0. 2. 4.]
 [1. 3. 5.]]
(2, 3)
